In [1]:
# Import ignore warnings

import warnings
warnings.filterwarnings('ignore')

In [2]:
# Importing libraries

import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [21]:
# Prep data

data = Path('../Resources/train_data_jan_day.csv')
df = pd.read_csv(data)
df.tail()

,Actual.Stop.Station,New.Trip.Name,Trip_date,Actual.Station.Dprt.Time,Segment.Direction,Trip.Name,Service.Line,Orig..Station,Dest..Station,Leading.Set.Type,Actual.Station.Dprt.Time.Band,Occupancy_Status,Occupancy_Range
24486,Zig Zag,W558-JOINED,1-Jan-19,54:43.0,Up,W558,West,Lithgow,Central,V,13:45-13:59,Many Seats Available,Low: 0-399
24487,Zig Zag,W565-JOINED,1-Jan-19,04:01.0,Down,W565,West,Central,Lithgow,V,19:00-19:14,Many Seats Available,Low: 0-399
24488,Zig Zag,W566-JOINED,1-Jan-19,54:05.0,Up,W566,West,Lithgow,Central,V,15:45-15:59,Many Seats Available,Low: 0-399
24489,Zig Zag,W574-JOINED,1-Jan-19,53:53.0,Up,W574,West,Lithgow,Central,V,17:45-17:59,Many Seats Available,Low: 0-399
24490,Zig Zag,W582-JOINED,1-Jan-19,54:12.0,Up,W582,West,Lithgow,Central,V,19:45-19:59,Many Seats Available,Low: 0-399

In [4]:
# Fill NaNs

df.fillna("", inplace=True)

In [5]:
# Create our features

df_features = df.drop(columns="Occupancy_Status")
X = pd.get_dummies(df_features)

# Create our target

y = df.Occupancy_Status

In [6]:
X.describe()

,Actual.Stop.Station_Aberdeen,Actual.Stop.Station_Adamstown,Actual.Stop.Station_Albion Park,Actual.Stop.Station_Allawah,Actual.Stop.Station_Arncliffe,Actual.Stop.Station_Artarmon,Actual.Stop.Station_Ashfield,Actual.Stop.Station_Asquith,Actual.Stop.Station_Auburn,Actual.Stop.Station_Austinmer,...,Actual.Station.Dprt.Time.Band_22:15-22:29,Actual.Station.Dprt.Time.Band_22:30-22:44,Actual.Station.Dprt.Time.Band_22:45-22:59,Actual.Station.Dprt.Time.Band_23:00-23:14,Actual.Station.Dprt.Time.Band_23:15-23:29,Actual.Station.Dprt.Time.Band_23:30-23:44,Actual.Station.Dprt.Time.Band_23:45-23:59,Occupancy_Range_High: Standing Room Only,Occupancy_Range_Low: 0-399,Occupancy_Range_Medium: 400-799
count,24491.000000,24491.000000,24491.000000,24491.000000,24491.000000,24491.000000,24491.000000,24491.000000,24491.000000,24491.000000,...,24491.000000,24491.000000,24491.000000,24491.000000,24491.000000,24491.000000,24491.000000,24491.000000,24491.000000,24491.000000
mean,0.000163,0.001021,0.001592,0.002654,0.002654,0.005349,0.007186,0.001429,0.006778,0.000980,...,0.012535,0.012821,0.011392,0.011719,0.011719,0.011923,0.010616,0.002205,0.959495,0.038300
std,0.012779,0.031934,0.039874,0.051450,0.051450,0.072942,0.084469,0.037777,0.082051,0.031289,...,0.111259,0.112504,0.106126,0.107618,0.107618,0.108541,0.102488,0.046905,0.197144,0.191923
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [7]:
# Check the balance of our target values

y.value_counts()

Many Seats Available    24105
Few Seats Available       297
                           62
Standing Room Only         27
Name: Occupancy_Status, dtype: int64

In [8]:
# Importing sklearn library
## Create X_train, X_test, y_train, y_test

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y)
X_train.shape

(18368, 6752)

In [9]:
# Create the StandardScaler instance

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [10]:
# Fit the Standard Scaler with the training data
# When fitting scaling functions, only train on the training dataset

X_scaler = scaler.fit(X_train)

In [11]:
# Scale the training and testing data

X_train_scale = X_scaler.transform(X_train)
X_test_scale = X_scaler.transform(X_test)

In [12]:
# Importing Logistic regression library

from sklearn.linear_model import LogisticRegression

## Fitting logisitic Regression to training data

model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_train, y_train)

LogisticRegression(random_state=1)

In [13]:
# Importing Balanced Accuracy Score library

from sklearn.metrics import balanced_accuracy_score

## Calculated the balanced accuracy score

y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.7369047992803386

In [14]:
# Importing confusion matrix library

from sklearn.metrics import confusion_matrix

## Display the confusion matrix

confusion_matrix(y_test, y_pred)

array([[  12,    0,    4,    0],
       [   0,   36,   37,    1],
       [   0,   19, 6007,    0],
       [   0,    2,    0,    5]], dtype=int64)

In [15]:
# Importing Classification Report (imbalanced)

from imblearn.metrics import classification_report_imbalanced

## Print the imbalanced classification report
## Based on y_test and y_pred data

print(classification_report_imbalanced(y_test, y_pred))

                            pre       rec       spe        f1       geo       iba       sup

                           1.00      0.75      1.00      0.86      0.87      0.73        16
 Few Seats Available       0.63      0.49      1.00      0.55      0.70      0.46        74
Many Seats Available       0.99      1.00      0.58      1.00      0.76      0.60      6026
  Standing Room Only       0.83      0.71      1.00      0.77      0.85      0.69         7

         avg / total       0.99      0.99      0.58      0.99      0.76      0.60      6123

In [16]:
# Importing Random Forest Classifier 

from imblearn.ensemble import BalancedRandomForestClassifier

## Resample the training data with the BalancedRandomForestClassifier

brf = BalancedRandomForestClassifier(n_estimators=1000, random_state=1)
brf.fit(X_train, y_train)

BalancedRandomForestClassifier(n_estimators=1000, random_state=1)

In [17]:
# Calculated the balanced accuracy score

y_pred_brf = brf.predict(X_test)
balanced_accuracy_score(y_test, y_pred_brf)

0.9411816811833407

In [18]:
# Display the confusion matrix

confusion_matrix(y_test, y_pred_brf)

array([[  16,    0,    0,    0],
       [   0,   63,    1,   10],
       [ 225,  205, 5504,   92],
       [   0,    0,    0,    7]], dtype=int64)

In [19]:
# Print the imbalanced classification report

print(classification_report_imbalanced(y_test, y_pred_brf))

                            pre       rec       spe        f1       geo       iba       sup

                           0.07      1.00      0.96      0.12      0.98      0.97        16
 Few Seats Available       0.24      0.85      0.97      0.37      0.91      0.81        74
Many Seats Available       1.00      0.91      0.99      0.95      0.95      0.90      6026
  Standing Room Only       0.06      1.00      0.98      0.12      0.99      0.98         7

         avg / total       0.99      0.91      0.99      0.94      0.95      0.90      6123

In [20]:
# List the features sorted in descending order by feature importance
## Then displaed the first 10 feature importances

importances = brf.feature_importances_
importances_sort = sorted(zip(brf.feature_importances_, X.columns), reverse=True)
importances_sort[:10]

[(0.052943683789356336, 'Occupancy_Range_Low: 0-399'),
 (0.042800624019887185, 'Leading.Set.Type_'),
 (0.04116235519967326, 'Occupancy_Range_Medium: 400-799'),
 (0.040473417157513986, 'Occupancy_Range_High: Standing Room Only'),
 (0.038545046776606966, 'New.Trip.Name_2--L-JOINED'),
 (0.02921412044246313, 'Service.Line_Bankstown'),
 (0.020387107948128192, 'Trip.Name_2--N'),
 (0.017835602636955113, 'Leading.Set.Type_T'),
 (0.015049377545853532, 'Leading.Set.Type_A'),
 (0.014333220221242155, 'Service.Line_Eastern Suburbs')]